### ISSUE TITLE
Directed graph edges overlap

### ISSUE THREAD

**Issue by mostafa-abdullah** [mostafa-abdullah/graph-test-cases#3]
Scenario (Directed):
- Add an edge between node 0 and 1
- Add an edge between node 1 and 0
- Remove the edge between node 0 and 1
- Re add the edge between node 0 and 1
- The two edges overlap

**Comment by HazemSamir** [comment]
I am sorry, check the pull request now, I suppose I fixed it. I made both edges drawn as curves

**Comment by HazemSamir** [comment]
well, it is not big issue but the edges still overlap if we made the two nodes close to each other.

![screenshot from 2016-05-27 13 25 59](https://cloud.githubusercontent.com/assets/12578145/15606880/312fd838-240f-11e6-8d34-164f370ed423.png)

I think it may be fixed by making the `curviness` parameter inversely proportional to the distance between the two nodes

[`connector = ['StateMachine', { curviness:20 }];`](https://github.com/mostafa-abdullah/graph-test-cases/blob/master/main.js#L124)
